package part11.ErrorHandling;

import javax.naming.NameAlreadyBoundException;

public class throwExceptions {

    public throwExceptions(int number)
    public static void main(String[] args) throws Exception {
       
    }
    
}
